# Generated by Django 4.2.11 on 2024-05-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpaceImages',
            new_name='SpaceImage',
        ),
    ]
